config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'tasks#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post '/tasks/:id' => 'tasks#change' 
  get '/tasks/:id/shared' => 'tasks#shared'
  resources :users
  resources :tasks do
    member do
      get 'shared'
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :users
  default_scope -> { order(created_at: :desc) }
  validates :content, :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
	
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  include Pundit
  protect_from_forgery

  private

    # Confirm a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy
	
  def index
    @tasks = Task.all.paginate(page: params[:page])
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "Task created!"
      redirect_to root_url
    else
      @tasks = Task.all.paginate(page: params[:page])
      render 'tasks/index'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      flash[:success] = "Task updated"
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def share
    @task = Task.find(params[:id])
  end

  #Adding more users to the task
  def editing
    @task.users << @user
  end

  # Action for share task
  def change
    @task = Task.find(params[:id])
    @user = User.find_by(email: params[:user][:email])
    unless @task.users.include?(@user)
      editing
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  # Action for showing sharing form
  def show
    @task = Task.find(params[:id])
  end

  # Action for showing contributors
  def shared
    @task = Task.find(params[:id])
  end

  def destroy
    @task.destroy
    flash[:success] = "Task deleted"
    redirect_to request.referrer || root_url
  end

  private

    def task_params
      params.require(:task).permit(:content)
    end

    def correct_user
      @task = current_user.tasks.find_by(id: params[:id])
      redirect_to root_url if @task.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the task manager!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns true if the given user is the current user
  def current_user?(user)
    user == current_user
  end

  # Returns the current logged-in user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user
  def log_out
  session.delete(:user_id)
    @current_user = nil
  end

  # Stores the URL trying to be accessed
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Task Manager by Mary Lutsyuk
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Log in", login_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "just do it!", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Just Do It!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js">
      </script>
      <script src="https://oss.maxcnd.com/respond/1.4.2/respond.min.js">
      </script>
  <![endif]-->
  <%= render 'layouts/header' %>
</head>
<body>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>

  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_task_form.html.erb
<%= form_for(@task) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new task..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>

app/views/tasks/_task.html.erb
<li id="task-<%= task.id %>">
  <%= link_to gravatar_for(task.user, size: 50), task.user %>
  <span class="user"><%= link_to task.user.name, task.user %></span>
  <span class="content">
    <%= task.content %>
  </span>
  <span class="timestamp">
    Created <%= time_ago_in_words(task.created_at) %> ago.
    <% if policy(task).update? %>
      <%= link_to "Delete", task, method: :delete, data: { confirm: "You sure?" } %>
      <%= link_to "Edit", edit_task_path(task) %>
      <%= link_to "Share", task_path(task) %>
    <% end %>
    <%= link_to "Contributors", shared_task_path(task) %>
  </span>
</li>

app/views/tasks/_tasks.html.erb
<li id="task-<%= task.id %>">
	<%= link_to gravatar_for(task.user, size: 50), task.user %>
	<span class="user"><%= link_to task.user.name, task.user %></span>
	<span class="content">
		<%= task.content %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(task.created_at) %> ago.
	</span>
</li>

app/views/tasks/edit.html.erb
<h1>Update your task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@task) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="task_form">
        <%= render 'shared/task_form' %>
      </section>
    </aside>
		<div class="col-md-8">
      <h3>Tasks (<%= @tasks.count %>)</h3>
      <ol class = "tasks">
        <%= render @tasks %>
      </ol>
      <%= will_paginate @tasks %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Task Manager</h1>
    <h2>
      Make your life easier!
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/tasks/share.html.erb
<h1>Share your task</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@task) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.submit "Share", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/tasks/shared.html.erb
<h1>Contributors</h1>
<% if @task.users.any? %>
  <div  class="row">
    <aside class="col-md-4">
      <ul class="users">
        <% @task.users.each do |user| %>
          <li>
            <%= gravatar_for user, size: 50 %>
            <%= link_to user.name, user %>
          </li>
        <% end %>
      </ul>
    </aside>
  </div>
<% else %>
  <h2>Oops! This task does not have contributors yet. Please, try another task ^_^</h2>
<% end %>

app/views/tasks/show.html.erb
<h1>Share your task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(User.new, url: task_path(@task)) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :task_id %>

      <%= f.label :email, "User's email for sharing" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Share", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>